wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720677998
    t:
      1:
      - 1
      - 55
      - 86
      - 105
      2:
      - 1
      - 55
      - 86
      - 105
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.17.2
      8:
      - 1
      - 5
      13: linux-x86_64
